# Generated by Django 6.1 on 2026-08-15 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('KONOBAR', 'Konobar')], default='KONOBAR', max_length=10)),
                ('display_name', models.CharField(blank=True, help_text='Emri që shfaqet në ekran (p.sh. te tavolina). Bosh = username.', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil stafi',
                'verbose_name_plural': 'Profilet e stafit',
            },
        ),
    ]
