# Generated by Django 6.1 on 2026-08-21 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_cashfloat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("CASH", "Gotovina"), ("CARD", "Kartica"), ("EUR", "Eur")],
                max_length=10,
            ),
        ),
    ]
